### ISSUE TITLE
Warning: React does not recognize the `data-testId` prop on a DOM element.  on the result page

### ISSUE THREAD

**Issue by sophiajwchoi** [myrithok/James#38]
## Expected Behavior
On the result page, the user shouldn't see the below error log in the chrome console.

## Actual Behavior

index.js:1 Warning: React does not recognize the `data-testId` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `data-testid` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at button
    at ButtonBase (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/0.chunk.js:13431:22)
    at WithStyles(ForwardRef(ButtonBase)) (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/0.chunk.js:49193:31)
    at Button (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/0.chunk.js:13173:24)
    at WithStyles(ForwardRef(Button)) (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/0.chunk.js:49193:31)
    at div
    at div
    at ResultsContainer (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/main.chunk.js:3421:3)
    at div
    at App (http://ec2-35-183-97-235.ca-central-1.compute.amazonaws.com/static/js/main.chunk.js:257:83)

## Steps to Reproduce the Problem

  1. Upload a text file
  1. Open up a chrome console
  
## Specifications

  - Platform: Windows chrome

**Comment by myrithok** [comment]
Thank you! Fixed in commit dc17c25125b0eb126102944fcf121e98d590b94c
